apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-conf-volume 
  annotations: 
     volume.beta.kubernetes.io/storage-class: "gitlab-sc"
  namespace: norman-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi 
  