apiVersion: apps/v1  
kind: DaemonSet 
metadata: 
  name: nginx-daemonset 
  namespace: kube-system 
  labels: 
    app: nginx 
spec: 
  selector: 
    matchLabels: 
      app: nginx 
  template: 
    metadata: 
      labels: 
        app: nginx 
    spec:
      tolerations: 
      - key: node-role.kubernetes.io/master 
        effect: NoSchedule
      containers: 
      - name: nginx 
        image: nginx:1.9.1 
        ports: 
        - containerPort: 80
