---
apiVersion: v1 
kind: Pod 
metadata: 
  name: config-test-pod 
spec: 
  containers: 
    - name: test-container 
      image: busybox 
      command: [ "/bin/sh", "-c", "enc" ] 
      env: 
        - name: WHAT_SCHOOL 
          valueFrom: 
            configMapKeyRef: 
              name: my-map 
              key: school 
  restarPolicy: Never 
