apiVersion: v1 
kind: ServiceAccount 
metadata: 
  name: gitlab-runner 
  namespace: norman-test
---
apiVersion: rbac.authorization.k8s.io/v1 
kind: Role
metadata: 
  namespace: norman-test 
  name: gitlab-runner 
rules:  
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log", "secrets"] 
    verbs: ["*"] 
--- 
apiVersion: rbac.authorization.k8s.io/v1beta1 
kind: RoleBinding 
metadata: 
  name: gitlab-runner 
  namespace: norman-test 
subjects: 
- kind: ServiceAccount 
  name: gitlab-runner 
  namespace: norman-test 
roleRef: 
  kind: Role 
  name: gitlab-runner 
  apiGroup: ""