apiVersion: storage.k8s.io/v1 
kind: StorageClass 
metadata: 
  name: gitlab-sc 
provisioner: kubernetes.io/aws-ebs
parameters: 
  type: gp2 
  encrypted: "true" 
  kmsKeyId: arn:aws:kms:us-east-1:492865049799:alias/aws/ebs
reclaimPolicy: Retain 
volumeBindingMode: Immediate