apiVersion: v1 
kind: ServiceAccount 
metadata: 
  name: gitlab-backup 
  namespace: norman-test
---
apiVersion: rbac.authorization.k8s.io/v1 
kind: Role
metadata: 
  namespace: norman-test 
  name: gitlab-backup 
rules:  
  - apiGroups: [""]
    resources: ["pods", "pods/exec"] 
    verbs: ["*"] 
--- 
apiVersion: rbac.authorization.k8s.io/v1beta1 
kind: RoleBinding 
metadata: 
  name: gitlab-backup 
  namespace: norman-test 
subjects: 
- kind: ServiceAccount 
  name: gitlab-backup 
  namespace: norman-test 
roleRef: 
  kind: Role 
  name: gitlab-backup 
  apiGroup: ""