--- 
apiVersion: batch/v1beta1 
kind: CronJob
metadata: 
  name: gitlab-daily-secrets-backup 
  namespace: norman-test
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  jobTemplate: 
    spec: 
      template:
        spec:
          serviceAccountName: gitlab-backup
          containers: 
          - name: gitlab-backup-secrets-job 
            image: 492865049799.dkr.ecr.us-east-1.amazonaws.com/quovo-kubectl:1.1.0
            args: 
            - /bin/sh 
            - -c 
            - aws s3 cp "/backup/gitlab/gitlab-secrets.json" s3://quovo-gitlab-backups/secrets/gitlab-secrets.$(date +%s).json 
            volumeMounts: 
            - mountPath: /backup/gitlab 
              name: gitlab-conf-volume
          restartPolicy: Never
          volumes: 
          - name: gitlab-conf-volume 
            persistentVolumeClaim: 
              claimName: gitlab-conf-volume  